### ISSUE TITLE
Seed the GWELLS Database for Testing

### ISSUE THREAD

**Issue by LolandaE** [bcgov/gwells#2160] opened 2024-02-15 18:05 UTC
**Describe the task**
To get some useful (more robust) fake data populated into GWELLS locally. Use PROD data and sanitize it (remove identifiers).

**Purpose**
This will help developers in GWELLS testing.

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by LocalNewsTV** [comment] 2024-03-21 17:47
This ticket is a duplicate of #2125

**Closed by LocalNewsTV** 2024-03-21 17:47 UTC
Labels: Task, Duplicate
